---
title: "Land use and microbe prevalence jointly determine host-microbe network structure"
subtitle: "Figures for paper"
author: "Matan Markfeld"
date: "Last edit: 2024-04-18"
output: 
  html_document:
    toc: true
    toc_float: true
    collapse: false
    number_sections: true
    code_folding: hide
    highlight: tango
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(results = "asis", message=FALSE, warning=FALSE, cache=TRUE, eval = TRUE, dev = c('png'), out.width = '100%', out.height='40%')
```


```{r load libraries, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(vegan)
library(igraph)
library(reshape2)


rm(list=ls())
```

```{r, reading data}
# reading the modules data

data_modules <- read_csv("../results/modules_table_three_villages.csv") 
```

# Figure 1

```{r}
data_modules_mandena <- data_modules %>% 
  filter(village=="Mandena")

# modules size
modules_size <- data_modules_mandena %>% 
  group_by(host_group) %>% 
  summarise(n = n_distinct(host_ID)) %>% 
  mutate(n = sqrt(n))

# preparing the pie charts data
# a list of host abundance in the 7 grids for every module

modules_pie <- data_modules_mandena %>% 
  group_by(host_group, grid) %>% 
  summarise(n = n_distinct(host_ID)) %>% 
  spread(grid, n, fill = 0) %>% 
  column_to_rownames("host_group") %>% 
  as.matrix()
# converting to list
module_pie_list <- split(modules_pie, seq(nrow(modules_pie)))

# building the network
# calculating the edges by betaNTI
# edge between modules = mean betaNTI values between all the individuals in the two modules
betaNTI_final_mandena <- betaNTI_three_villages %>% 
    mutate(same_module = ifelse(host_group1==host_group2, "Same","Different")) %>% 
  filter(village == "Mandena" & same_module == "Different") %>% 
    mutate(host_group1_org = host_group1) %>% 
  rowwise() %>%
  mutate(host_group1 = sort(c(host_group1, host_group2))[1], host_group2 = sort(c(host_group1_org, host_group2))[2]) %>% 
  group_by(host_group1, host_group2) %>% 
  summarise(mean_betaNTI = mean(sqrt(betaNTI))) %>%   
  mutate(rescale_betaNTI = ifelse(mean_betaNTI>0.5, 0, mean_betaNTI)) %>% 
  #filter(rescale_betaNTI != 0) %>% 
  mutate(rescale_betaNTI = (1-scales::rescale(mean_betaNTI,to=c(0,1)))*10)  
   # rescale the values

# igraph
data_for_graph <- betaNTI_final_mandena %>% select(-mean_betaNTI)
modules_graph <- graph_from_data_frame(data_for_graph, directed = FALSE)

# graph color
library("RColorBrewer")
colo <- brewer.pal(n = 7, name = "Spectral")
colo <- c("#f9c74f","#f94144", "#4d908e", "#277da1", "#90be6d", "#00916e", "#766153")
V(modules_graph)$pie.color=list(colo)

set.seed(123)
l <- layout_with_fr(modules_graph) 
l <- norm_coords(l, ymin=-3, ymax=3, xmin=-3, xmax=3)
plot(modules_graph,
     rescale=F,
     xlim = c(-3, 3),
  ylim = c(-3, 3.2),
     layout=l,
     vertex.shape="pie", 
     vertex.pie=module_pie_list,
     vertex.size=modules_size$n *10, 
     edge.curved=.1,
     vertex.label=NA)

```

